eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://150.242.14.145:3306/RUAMBOT_NEW
    username: Jenkin
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      naming : 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

UserDefaultPass: Apmosys@123

profile:
  lockCount: 5

ruambotBuild: 2.0   
